from core.module_base import ModuleBase
from scapy.all import sniff, IP, UDP, Raw
from datetime import datetime


class LLMNRNBTNSPoisonDetect(ModuleBase):
    """
    LLMNR & NetBIOS-NS Poisoning / Responder Sentinel.
    Detects spoofed LLMNR (UDP 5355) and NetBIOS Name Service (UDP 137) response
    bursts commonly generated by credential harvesting tools like Responder.
    """

    def __init__(self, session):
        super().__init__(session)
        self.options = {
            "INTERFACE": {"value": session.get_global("INTERFACE", "enp1s0"), "required": True, "desc": "Network interface to monitor"},
            "DURATION": {"value": "30", "required": True, "desc": "Monitoring duration in seconds (0 = continuous)"},
        }
        self.already_alerted = set()

    def _on_packet(self, pkt):
        if not (pkt.haslayer(IP) and pkt.haslayer(UDP)):
            return

        udp = pkt[UDP]
        if udp.dport not in (5355, 137) and udp.sport not in (5355, 137):
            return

        ip = pkt[IP]
        src = ip.src
        dst = ip.dst

        if self.session.is_whitelisted(src):
            return

        # Check for rapid unsolicited responses
        if udp.sport in (5355, 137):
            key = (src, "LLMNR_POISON")
            if key not in self.already_alerted:
                self.already_alerted.add(key)
                ts = datetime.now().strftime("%H:%M:%S")
                proto = "LLMNR" if udp.sport == 5355 else "NetBIOS-NS"
                print(f"[ALERT] {proto} Spoofing / Poisoning Probe: {src} -> {dst} [{ts}]")

                self.session.add_alert({
                    "type": f"{proto}_POISONING_ATTACK",
                    "severity": "HIGH",
                    "confidence": 0.93,
                    "mitre_id": "T1557.001",
                    "source": src,
                    "destination": dst,
                    "protocol": proto,
                    "description": f"Potential {proto} poisoning / Responder credential theft attack from {src} against {dst}",
                    "details": {
                        "source_port": udp.sport,
                        "destination_port": udp.dport,
                    }
                })

    def run(self):
        iface = self.options["INTERFACE"]["value"] or self.session.get_global("INTERFACE", "enp1s0")
        duration = int(self.options["DURATION"]["value"])

        self.already_alerted.clear()
        print(f"[*] LLMNR / NetBIOS Poisoning Sentinel active on {iface}...")

        try:
            sniff(iface=iface, filter="udp and (port 5355 or port 137)", prn=self._on_packet, timeout=duration if duration > 0 else None, store=0)
        except PermissionError:
            print("[-] Permission denied. Run ANDS with sudo.")
            return
        except KeyboardInterrupt:
            print("\n[*] LLMNR monitoring stopped.")
            return

        print(f"[+] LLMNR / NetBIOS Sentinel finished — {len(self.already_alerted)} incident(s) flagged.")
